vich_uploader:
    db_driver: orm

    mappings:
        icon_prestation:
            uri_prefix: /resources/icons/prestations
            upload_destination: '%kernel.project_dir%/public/resources/icons/prestations'

        icon_argument:
            uri_prefix: /resources/icons/arguments
            upload_destination: '%kernel.project_dir%/public/resources/icons/arguments'        

        # service_gallery:
        #     uri_prefix: /images/services/gallery
        #     upload_destination: '%kernel.project_dir%/public/images/services/gallery'    

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
